export default interface Camper {
    id: string,
    name: string,
    description: string,
    location: string,
    price: number,
    rating: number,
    form: string,
    AC: boolean,
    TV: boolean,
    kitchen: boolean,
    bathroom: boolean,
    radio: boolean,
    gas: boolean,
    engine: string,
    refrigerator: boolean,
    microwave: boolean,
    water: boolean,
    transmission: string,
    reviews: {reviewer_name: string, reviewer_rating: number, comment: string,}[],
    gallery: {thumb: string, original: string}[],
}