export default interface Camper {
    id: string,
    name: string,
    description: string,
    location: string,
    price: number,
    rating: number,
    form: string,
    AC: boolean,
    TV: boolean,
    kitchen: boolean,
    bathroom: boolean,
    radio: boolean,
    gas: boolean,
    petrol: boolean,
    refrigerator: boolean,
    microwave: boolean,
    water: boolean,
    automatic: boolean,
    reviews: {reviewer_name: string, reviewer_rating: number, comment: string,},
    gallery: string[] | string,
}